baseURL = "https://example.org/"
languageCode = "en-us"
title = "My Mirantis-Style Blog"
theme = "pehtheme-hugo"

[params]
  author = "Your Name"
  description = "Blog styled after Mirantis branding"
  logo = "/images/logo-mirantis.svg"
  logoAlt = "Mirantis"
  primaryColor = "#D81B60"
  bgColor = "#0D1B2A"
  navBgColor = "#0B1622"
  textColor = "#FFFFFF"
  enableSearch = true
  showReadingTime = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
